baseURL = 'https://vivekm.in'
languageCode = 'en-us'
title = 'Vivek Mishra - Software Engineer'
theme = 'ritzy'
themesDir = "themes/"

[params]
  author = "Vivek Mishra"
  description = "Engineer and Designer based in India, built 10+ web and mobile applications for Fortune 500 companies."

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
 